### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by N-Kingsley** [chenxy99/Generative-Temporal-Models-with-Spatial-Memory#1]
when i run the code , the error is as follows, 
>>> import pyflann
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ni/anaconda2/envs/python34/lib/python3.6/site-packages/pyflann-1.6.13-py3.6.egg/pyflann/__init__.py", line 27, in <module>
ModuleNotFoundError: No module named 'index'
index library is installed,but it doesn't make. How should i use the pyflann?

**Comment by chenxy99** [comment]
I have met the similar error at the begining of my implementation. You can try to re-install the pyflann by using:
conda install -c conda-forge pyflann

**Comment by N-Kingsley** [comment]
Thank you for your help.I have solved this problem. And I what to ask how the 'kld loss' and 'matrix loss' in the model.py. I can't understand this part of the code.

**Comment by chenxy99** [comment]
The 'kld loss' is the second term (an expected KL divergence for the VAE) of the ELBO in page 5. Actually, the divergence between Gaussian distribution and mixture Gaussian distribution has no a close form, so I used Monte Carlo method to calculate its value.

The  'matrix loss' is another regularization I add in my simulation, so that the two coordinate axises of the inferred states s can be mutually perpendicular and have uniformly-step.

**Comment by N-Kingsley** [comment]
In the model.py, the 'log_normalized_wk ' is the formula in appendix A.1?
And the line 301 to 313 estimated KL divergence，but I can't understand fully. Can you explain or recommend a paper or website about the algorithm?

**Comment by chenxy99** [comment]
Yes, the 'normalized_wk ' is the formula in appendix A.1 and the 'log_normalized_wk ' is the logarithm of normalized_wk.

Actually, line 291 to 313 is used to estimate KL divergence. 
Line 291 to 294 is used to extract information from the memory.
Line 295 to 298 is used to calculate the 'log_normalized_wk ' in appendix A.1.
Line 299 to 300 is used to sample the multi-Gaussian distribution from distribution q_phi.
Line 301 to 302 is used to calculate the entropy of the multi-Gaussian distribution.
Line 303 to 307 is used to collect the mean value and variance of the mixture multi-Gaussian distribution.
Lind 308 to 309 is used to calculate each element of the log PDF of the mixture multi-Gaussian distribution.
Line 310 to 312 is used to calculate the cross-entropy between Gaussian distribution and mixture multi-Gaussian distribution at the mean time it can prevent numerical instability。

**Comment by N-Kingsley** [comment]
-KL(q_phi||p_theta)=H(q_phi)-H(p_theta, q_phi)
Is the 'log_q_phi' the entropy of -H(q_phi) not H(q_phi) ?
Is the 'log_p_theta_element'  the formula about the value of log(p_theta) in appendix A.1?
But I still can't understand line 308 to 313.
Why to do the operation of  'torch.max()' ?

**Comment by chenxy99** [comment]
log_q_phi is the -H(q_phi).
The 'log_p_theta_element' the formula about the K elements in p_theta, that is log(wkN(zt|z(k))).
Why to do the operation of 'torch.max()' ?
Because for the numerical stability. For example, if we want to directly calculate the softmax of 10000, 1, we may achieve Nan at last. So we should subtract them by 10000, and then calculate the softmax of 0, -9999, we will finally obtain 1, 0.
