### ISSUE TITLE
Question about calculating KL

### ISSUE THREAD

**Issue by seann999** [chenxy99/Generative-Temporal-Models-with-Spatial-Memory#4]
Sorry if this is a basic question; variational inference isn't my forte. When calculating the KL divergence, it seems like the code takes 1000 samples from Q and roughly calculates the mean of log(Q(sample) / P(sample)).  (I'm probably wrong about some part.)

Is it not possible to directly calculate the KL divergence since we have both mean and std for Q and P, which I think are both Gaussian?

**Comment by chenxy99** [comment]
If the KL divergence between Q and P which are both Gaussian with known mean and std, this KL divergence can have a close form (Equation 6 in [Tutorial on Variational Autoencoders](https://arxiv.org/pdf/1606.05908.pdf)).
However, if P is the mixed gaussian distribution ([Page 11 A.1. Image navigation experiment](https://arxiv.org/pdf/1804.09401.pdf)) and Q is the gaussian distribution, the KL divergence of P and Q does not have a close form. Since Integrate(Plog(Q/P)) does not have close form, so it is not possible to directly calculate the KL divergence of them.

**Comment by seann999** [comment]
Oh, I had forgotten that P was a mixture model. Thanks!
