### ISSUE TITLE
log_q term correctness

### ISSUE THREAD

**Issue by sepehrjng92** [chenxy99/Generative-Temporal-Models-with-Spatial-Memory#5]
Hi Xianyu,

Thanks a lot for sharing your implementation of GTM-SM. I had one questions:
1- I don't totally understand why the log_q_phi  is:
######
log_q_phi = - 0.5 * self.z_dim * torch.log(2*pi) - 0.5 * self.z_dim - torch.log(zt_std_prediction_tensor[:,index_sample]).sum(1)
######

and not equal to:
######
log_q_phi = - 0.5 * self.z_dim * torch.log(2 * pi) - 0.5 * torch.log(zt_std_prediction_tensor[:,index_sample]).sum(1).unsqueeze(0) - 0.5 * (((zt_sampling - zt_mean_prediction_tensor[:, index_sample].unsqueeze(0))/zt_std_prediction_tensor[:, index_sample].unsqueeze(0))**2).sum(2)
######

as we need another term for the quadratic difference of the sampled latent and the inferred mean. Am I misunderstanding something here?

**Comment by chenxy99** [comment]
Since it is in the kl divergence and q_phi is a Multivariate Gaussian distribution, and in kl divergence is the integration of int(q_phi * log_q_phi). I may be a little lazy to use log_q_phi  to represent int(q_phi * log_q_phi) instead of a more precise version ‘int_ log_q_phi’.
Because int_ log_q_phi has a close form - 0.5 * self.z_dim * torch.log(2*pi) - 0.5 * self.z_dim - torch.log(zt_std_prediction_tensor[:,index_sample]).sum(1) as mentioned in line 301 in model.py. I use the theoretical integration result instead of the sum of the sampling because the theoretical integration result may be more precise than the sum of the sampling.  

However for log_p_theta_element in line 308 in model.py. It is a complex term because it is a mixed Gaussian distribution and has no close form for int(p_theta * log_p_theta). So I have to use sampling method to calculate the numerical result of int(p_theta * log_p_theta).

**Comment by sepehrjng92** [comment]
Thanks a lot. That makes sense
